add_newline = true

[character]
error_symbol = "[ & ](bold red)"
success_symbol = "[ & ](bold green)"

[directory]
read_only = " ðŸ”’"
truncation_symbol = "â€¦/"

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false
style = "bold purple"

[username]
format = "[$user]($style)@"
show_always = true
